language: node_js
node_js: node
script: yarn build
before_deploy:
  - jq ".version=\"1.0.$TRAVIS_BUILD_NUMBER\"" build/manifest.json > manifest_v.json
  - mv manifest_v.json build/manifest.json
deploy:
  provider: script
  skip_cleanup: true
  script: node ./deploy.js
  on:
    branch: master